### ISSUE TITLE
How does it work with multiple translations?

### ISSUE THREAD

**Issue by Haroenv** [vinhlh/tagged-translations#3]
I don't see documented how the process goes if there are multiple possible languages the text needs to be translated to. How is that controlled?

**Comment by vinhlh** [comment]
Hi @Haroenv,
Currently, I am doing this way via `babel-plugin-macros`:
```js
// babel-plugin-macros.config.js
const { REACT_APP_LANGUAGE: language } = process.env

module.exports = {
  taggedTranslations: {
    tagName: 't',
    translationFile: `./src/translations/buildTime/${language}.json`
  }
}
```

We could do a similar thing with `.babelrc.js`. Let me update the doc.
Or there is any better way that you would like to have/ recommend?

**Comment by Haroenv** [comment]
Cool 👍 just documenting that in the readme would be clear enough
